import { TRPCError } from '@trpc/server';
import type { TRPC_ERROR_CODE_KEY } from '@trpc/server/rpc';

export const APP_ERROR_MESSAGES = [
  'UNKNOWN_ERROR',
  'VALIDATION_ERROR',
  'UNAUTHENTICATED',
  'FORBIDDEN',
  'USER_MISMATCH',
  'NOT_CLUB_ADMIN',
  'NOT_TOURNAMENT_ORGANIZER',
  'CANNOT_LEAVE_ONLY_CLUB',
  'NOT_ENOUGH_TOURNAMENT_UNITS',
  'PAIRING_GENERATOR_ERROR',
  'RATING_CALCULATION_ERROR',
  'LICHESS_API_ERROR',
  'CONFIG_ERROR',
  'DATABASE_MIGRATION_ERROR',
  'AFFILIATION_EXISTS',
  'AFFILIATION_NOT_FOUND',
  'AFFILIATION_STATUS_NOT_REQUESTED',
  'ALREADY_AFFILIATED',
  'CLUB_ID_NOT_MATCHING',
  'CLUB_MISMATCH',
  'CLUB_NOT_CREATED',
  'CLUB_NOT_DELETED',
  'CLUB_NOT_FOUND',
  'CONCURRENT_GAME_RESULT_UPDATE',
  'EMPTY_CLUB_EXISTS',
  'GAME_NOT_FOUND',
  'INCOMPLETE_GAMES',
  'INVALID_DOUBLES_PAIR',
  'INVALID_PRE_START_WITHDRAWN_UNIT',
  'INVALID_ROUNDS_NUMBER',
  'INVALID_UNITS_ORDER',
  'INVALID_UNIT_IN_PAIRING',
  'LONG_CLUB_NAME',
  'MAX_50',
  'MAX_NICKNAME_LENGTH',
  'MAX_PEAK_RATING',
  'MAX_RATING',
  'MIN_NICKNAME_LENGTH',
  'MIN_PEAK_RATING',
  'MIN_RATING',
  'LICHESS_TEAM_ALREADY_LINKED',
  'LINK_TEAM_ERROR',
  'NOT_DOUBLES_TOURNAMENT',
  'NOT_LICHESS_TEAM_ADMIN',
  'NOT_SOLO_TOURNAMENT',
  'NOT_SWISS_TOURNAMENT',
  'NOT_YOUR_GAME',
  'NO_AFFILIATION',
  'NO_OTHER_CLUB_CO_OWNER',
  'NO_TOURNAMENT_DATA',
  'NO_UNITS_DATA',
  'PASTE_DISABLED',
  'PAIR_PLAYERS_NOT_FOUND',
  'PLAYER_ALREADY_IN_PAIR',
  'PLAYER_ALREADY_IN_UNIT',
  'PLAYER_EXISTS_ERROR',
  'PLAYER_HAS_TOURNAMENTS',
  'PLAYER_NOT_CREATED',
  'PLAYER_NOT_EDITED',
  'PLAYER_NOT_FOUND',
  'PLAYER_RESULT_SETTING_DISABLED',
  'RELATION_EXISTS',
  'ROUND_ALREADY_HAS_RESULTS',
  'SESSION_VALIDATION_TIMEOUT',
  'SHORT_CLUB_NAME',
  'TOURNAMENT_ALREADY_FINISHED',
  'TOURNAMENT_ALREADY_RESET',
  'TEAM_PLAYERS_SHOULD_BE_DIFFERENT',
  'TOURNAMENT_ALREADY_STARTED',
  'TOURNAMENT_NOT_CREATED',
  'TOURNAMENT_INFO_NOT_LOADED',
  'TOURNAMENT_NOT_FOUND',
  'TOURNAMENT_NOT_STARTED',
  'TIME_TRAVEL',
  'TOURNAMENT_UNIT_IDS_NOT_UNIQUE',
  'TOURNAMENT_UNIT_NOT_FOUND',
  'UNIT_ALREADY_WITHDRAWN',
  'UNIT_NOT_ADDED',
  'UNIT_NOT_REMOVED',
  'UNIT_NOT_WITHDRAWN',
  'UNIT_NICKNAME_TAKEN',
  'UNIT_PLAYERS_NOT_FOUND',
  'UNSUPPORTED_TOURNAMENT_FORMAT',
  'USERS_NOT_LOADED',
  'USERID_NOT_FOUND_IN_CONTEXT',
  'USER_NOT_FOUND',
  'WITHDRAWAL_REDUCES_ROUNDS_BELOW_CURRENT',
  'WITHDRAWN_UNIT_CANNOT_PLAY',
  'POSSIBLE_PLAYERS_NOT_LOADED',
  'TOURNAMENT_UNITS_NOT_LOADED',
  'WEBSOCKET_FAILED',
  'WEBSOCKET_MESSAGE_NOT_SENT',
  'ZERO_CLUBS',
] as const;

export type AppErrorMessage = (typeof APP_ERROR_MESSAGES)[number];

export const isAppErrorMessage = (value: unknown): value is AppErrorMessage =>
  APP_ERROR_MESSAGES.includes(value as AppErrorMessage);

export const APP_ERROR_TRPC_CODES: Partial<
  Record<AppErrorMessage, TRPC_ERROR_CODE_KEY>
> = {
  UNAUTHENTICATED: 'UNAUTHORIZED',

  FORBIDDEN: 'FORBIDDEN',
  USER_MISMATCH: 'FORBIDDEN',
  NOT_CLUB_ADMIN: 'FORBIDDEN',
  NOT_TOURNAMENT_ORGANIZER: 'FORBIDDEN',
  NOT_LICHESS_TEAM_ADMIN: 'FORBIDDEN',
  NOT_YOUR_GAME: 'FORBIDDEN',

  AFFILIATION_NOT_FOUND: 'NOT_FOUND',
  CLUB_NOT_FOUND: 'NOT_FOUND',
  GAME_NOT_FOUND: 'NOT_FOUND',
  NO_AFFILIATION: 'NOT_FOUND',
  PAIR_PLAYERS_NOT_FOUND: 'NOT_FOUND',
  PLAYER_NOT_FOUND: 'NOT_FOUND',
  TOURNAMENT_NOT_FOUND: 'NOT_FOUND',
  TOURNAMENT_UNIT_NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'NOT_FOUND',

  AFFILIATION_EXISTS: 'CONFLICT',
  ALREADY_AFFILIATED: 'CONFLICT',
  CONCURRENT_GAME_RESULT_UPDATE: 'CONFLICT',
  EMPTY_CLUB_EXISTS: 'CONFLICT',
  LICHESS_TEAM_ALREADY_LINKED: 'CONFLICT',
  PLAYER_ALREADY_IN_PAIR: 'CONFLICT',
  PLAYER_ALREADY_IN_UNIT: 'CONFLICT',
  PLAYER_EXISTS_ERROR: 'CONFLICT',
  RELATION_EXISTS: 'CONFLICT',
  TOURNAMENT_ALREADY_FINISHED: 'CONFLICT',
  TOURNAMENT_ALREADY_RESET: 'CONFLICT',
  TOURNAMENT_ALREADY_STARTED: 'CONFLICT',
  UNIT_NICKNAME_TAKEN: 'CONFLICT',

  AFFILIATION_STATUS_NOT_REQUESTED: 'PRECONDITION_FAILED',
  CANNOT_LEAVE_ONLY_CLUB: 'PRECONDITION_FAILED',
  INCOMPLETE_GAMES: 'PRECONDITION_FAILED',
  INVALID_PRE_START_WITHDRAWN_UNIT: 'PRECONDITION_FAILED',
  INVALID_ROUNDS_NUMBER: 'PRECONDITION_FAILED',
  NO_OTHER_CLUB_CO_OWNER: 'PRECONDITION_FAILED',
  NOT_ENOUGH_TOURNAMENT_UNITS: 'PRECONDITION_FAILED',
  PLAYER_HAS_TOURNAMENTS: 'PRECONDITION_FAILED',
  PLAYER_RESULT_SETTING_DISABLED: 'PRECONDITION_FAILED',
  ROUND_ALREADY_HAS_RESULTS: 'PRECONDITION_FAILED',
  TOURNAMENT_NOT_STARTED: 'PRECONDITION_FAILED',
  UNIT_ALREADY_WITHDRAWN: 'PRECONDITION_FAILED',
  WITHDRAWAL_REDUCES_ROUNDS_BELOW_CURRENT: 'PRECONDITION_FAILED',
  WITHDRAWN_UNIT_CANNOT_PLAY: 'PRECONDITION_FAILED',
  ZERO_CLUBS: 'PRECONDITION_FAILED',

  CLUB_ID_NOT_MATCHING: 'UNPROCESSABLE_CONTENT',
  CLUB_MISMATCH: 'UNPROCESSABLE_CONTENT',
  INVALID_DOUBLES_PAIR: 'UNPROCESSABLE_CONTENT',
  INVALID_UNITS_ORDER: 'UNPROCESSABLE_CONTENT',
  INVALID_UNIT_IN_PAIRING: 'UNPROCESSABLE_CONTENT',
  NOT_DOUBLES_TOURNAMENT: 'UNPROCESSABLE_CONTENT',
  NOT_SOLO_TOURNAMENT: 'UNPROCESSABLE_CONTENT',
  NOT_SWISS_TOURNAMENT: 'UNPROCESSABLE_CONTENT',
  UNSUPPORTED_TOURNAMENT_FORMAT: 'UNPROCESSABLE_CONTENT',

  UNKNOWN_ERROR: 'INTERNAL_SERVER_ERROR',
  CONFIG_ERROR: 'INTERNAL_SERVER_ERROR',
  CLUB_NOT_CREATED: 'INTERNAL_SERVER_ERROR',
  PAIRING_GENERATOR_ERROR: 'INTERNAL_SERVER_ERROR',
  PLAYER_NOT_CREATED: 'INTERNAL_SERVER_ERROR',
  PLAYER_NOT_EDITED: 'INTERNAL_SERVER_ERROR',
  RATING_CALCULATION_ERROR: 'INTERNAL_SERVER_ERROR',

  LICHESS_API_ERROR: 'BAD_GATEWAY',

  SESSION_VALIDATION_TIMEOUT: 'TIMEOUT',
};

export const getAppErrorTrpcCode = (
  message: AppErrorMessage,
): TRPC_ERROR_CODE_KEY =>
  APP_ERROR_TRPC_CODES[message] ?? APP_ERROR_TRPC_CODES['UNKNOWN_ERROR']!;

export class AppError extends TRPCError {
  constructor(message: AppErrorMessage, options?: ErrorOptions) {
    super({ code: getAppErrorTrpcCode(message), message, ...options });
    this.name = 'AppError';
  }
}

export const getAppErrorMessage = (error: unknown): AppErrorMessage => {
  if (error instanceof AppError) return error.message as AppErrorMessage;
  if (error instanceof Error && isAppErrorMessage(error.message)) {
    return error.message;
  }
  if (isAppErrorMessage(error)) return error;
  return 'UNKNOWN_ERROR';
};
