import { TRPCError } from '@trpc/server';

import type { TRPC_ERROR_CODE_KEY } from '@trpc/server/rpc';

export const ERRORS = [
  'UNKNOWN_ERROR',
  'VALIDATION_ERROR',
  'UNAUTHENTICATED',
  'FORBIDDEN',
  'USER_MISMATCH',
  'NOT_CLUB_ADMIN',
  'NOT_TOURNAMENT_ORGANIZER',
  'CANNOT_LEAVE_ONLY_CLUB',
  'NOT_ENOUGH_TOURNAMENT_UNITS',
  'PAIRING_GENERATOR_ERROR',
  'RATING_CALCULATION_ERROR',
  'LICHESS_API_ERROR',
  'CONFIG_ERROR',
  'DATABASE_MIGRATION_ERROR',
  'DATE_TOO_FAR_AHEAD',
  'AFFILIATION_EXISTS',
  'AFFILIATION_NOT_FOUND',
  'AFFILIATION_STATUS_NOT_REQUESTED',
  'ALREADY_AFFILIATED',
  'CLUB_ID_NOT_MATCHING',
  'CLUB_MISMATCH',
  'CLUB_NOT_CREATED',
  'CLUB_NOT_DELETED',
  'CLUB_NOT_FOUND',
  'CONCURRENT_GAME_RESULT_UPDATE',
  'DOUBLES_TOURNAMENT_CANNOT_BE_RATED',
  'EMPTY_CLUB_EXISTS',
  'GAME_NOT_FOUND',
  'INCOMPLETE_GAMES',
  'INVALID_DATE',
  'INVALID_DOUBLES_PAIR',
  'INVALID_PRE_START_WITHDRAWN_UNIT',
  'INVALID_ROUNDS_NUMBER',
  'INVALID_UNITS_ORDER',
  'INVALID_UNIT_IN_PAIRING',
  'LONG_CLUB_NAME',
  'MAX_50',
  'MAX_NICKNAME_LENGTH',
  'MAX_PEAK_RATING',
  'MAX_RATING',
  'MIN_NICKNAME_LENGTH',
  'MIN_PEAK_RATING',
  'MIN_RATING',
  'LICHESS_TEAM_ALREADY_LINKED',
  'LINK_TEAM_ERROR',
  'NOT_DOUBLES_TOURNAMENT',
  'NOT_LICHESS_TEAM_ADMIN',
  'NOT_SOLO_TOURNAMENT',
  'NOT_SWISS_TOURNAMENT',
  'NOT_YOUR_GAME',
  'NO_AFFILIATION',
  'NO_OTHER_CLUB_CO_OWNER',
  'NO_TOURNAMENT_DATA',
  'NO_UNITS_DATA',
  'PASTE_DISABLED',
  'PAIR_PLAYERS_NOT_FOUND',
  'PLAYER_ALREADY_IN_PAIR',
  'PLAYER_ALREADY_IN_UNIT',
  'PLAYER_EXISTS_ERROR',
  'PLAYER_HAS_TOURNAMENTS',
  'PLAYER_NOT_CREATED',
  'PLAYER_NOT_EDITED',
  'PLAYER_NOT_FOUND',
  'PLAYER_RESULT_SETTING_DISABLED',
  'RELATION_EXISTS',
  'ROUND_ALREADY_HAS_RESULTS',
  'SESSION_VALIDATION_TIMEOUT',
  'SHORT_CLUB_NAME',
  'TOURNAMENT_ALREADY_FINISHED',
  'TOURNAMENT_ALREADY_RESET',
  'TEAM_PLAYERS_SHOULD_BE_DIFFERENT',
  'TOURNAMENT_ALREADY_STARTED',
  'TOURNAMENT_NOT_CREATED',
  'TOURNAMENT_INFO_NOT_LOADED',
  'TOURNAMENT_NOT_FOUND',
  'TOURNAMENT_NOT_STARTED',
  'TIME_TRAVEL',
  'TOURNAMENT_UNIT_IDS_NOT_UNIQUE',
  'TOURNAMENT_UNIT_NOT_FOUND',
  'UNIT_ALREADY_WITHDRAWN',
  'UNIT_NOT_ADDED',
  'UNIT_NOT_REMOVED',
  'UNIT_NOT_WITHDRAWN',
  'UNIT_NICKNAME_TAKEN',
  'UNIT_PLAYERS_NOT_FOUND',
  'UNSUPPORTED_TOURNAMENT_FORMAT',
  'USERS_NOT_LOADED',
  'USERID_NOT_FOUND_IN_CONTEXT',
  'USER_NOT_FOUND',
  'WITHDRAWAL_REDUCES_ROUNDS_BELOW_CURRENT',
  'WITHDRAWN_UNIT_CANNOT_PLAY',
  'POSSIBLE_PLAYERS_NOT_LOADED',
  'TOURNAMENT_UNITS_NOT_LOADED',
  'WEBSOCKET_FAILED',
  'WEBSOCKET_MESSAGE_NOT_SENT',
  'ZERO_CLUBS',
] as const;

export type AppErrorMessage = (typeof ERRORS)[number];

export const isAppErrorMessage = (value: unknown): value is AppErrorMessage =>
  ERRORS.includes(value as AppErrorMessage);

export const ERROR_TRPC_CODES: Record<AppErrorMessage, TRPC_ERROR_CODE_KEY> = {
  VALIDATION_ERROR: 'BAD_REQUEST',
  UNAUTHENTICATED: 'UNAUTHORIZED',

  FORBIDDEN: 'FORBIDDEN',
  USER_MISMATCH: 'FORBIDDEN',
  NOT_CLUB_ADMIN: 'FORBIDDEN',
  NOT_TOURNAMENT_ORGANIZER: 'FORBIDDEN',
  NOT_LICHESS_TEAM_ADMIN: 'FORBIDDEN',
  NOT_YOUR_GAME: 'FORBIDDEN',
  PLAYER_RESULT_SETTING_DISABLED: 'FORBIDDEN',

  AFFILIATION_NOT_FOUND: 'NOT_FOUND',
  CLUB_NOT_FOUND: 'NOT_FOUND',
  GAME_NOT_FOUND: 'NOT_FOUND',
  NO_AFFILIATION: 'NOT_FOUND',
  PAIR_PLAYERS_NOT_FOUND: 'NOT_FOUND',
  PLAYER_NOT_FOUND: 'NOT_FOUND',
  TOURNAMENT_NOT_FOUND: 'NOT_FOUND',
  TOURNAMENT_UNIT_NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'NOT_FOUND',

  AFFILIATION_EXISTS: 'CONFLICT',
  AFFILIATION_STATUS_NOT_REQUESTED: 'CONFLICT',
  ALREADY_AFFILIATED: 'CONFLICT',
  CANNOT_LEAVE_ONLY_CLUB: 'CONFLICT',
  CONCURRENT_GAME_RESULT_UPDATE: 'CONFLICT',
  DOUBLES_TOURNAMENT_CANNOT_BE_RATED: 'CONFLICT',
  EMPTY_CLUB_EXISTS: 'CONFLICT',
  INCOMPLETE_GAMES: 'CONFLICT',
  DATE_TOO_FAR_AHEAD: 'BAD_REQUEST',
  INVALID_DATE: 'BAD_REQUEST',
  INVALID_PRE_START_WITHDRAWN_UNIT: 'CONFLICT',
  INVALID_ROUNDS_NUMBER: 'CONFLICT',
  LICHESS_TEAM_ALREADY_LINKED: 'CONFLICT',
  NO_OTHER_CLUB_CO_OWNER: 'CONFLICT',
  NOT_ENOUGH_TOURNAMENT_UNITS: 'CONFLICT',
  PLAYER_ALREADY_IN_PAIR: 'CONFLICT',
  PLAYER_ALREADY_IN_UNIT: 'CONFLICT',
  PLAYER_EXISTS_ERROR: 'CONFLICT',
  PLAYER_HAS_TOURNAMENTS: 'CONFLICT',
  RELATION_EXISTS: 'CONFLICT',
  ROUND_ALREADY_HAS_RESULTS: 'CONFLICT',
  TOURNAMENT_ALREADY_FINISHED: 'CONFLICT',
  TOURNAMENT_ALREADY_RESET: 'CONFLICT',
  TOURNAMENT_ALREADY_STARTED: 'CONFLICT',
  TOURNAMENT_NOT_STARTED: 'CONFLICT',
  UNIT_ALREADY_WITHDRAWN: 'CONFLICT',
  UNIT_NICKNAME_TAKEN: 'CONFLICT',
  WITHDRAWAL_REDUCES_ROUNDS_BELOW_CURRENT: 'CONFLICT',
  WITHDRAWN_UNIT_CANNOT_PLAY: 'CONFLICT',
  ZERO_CLUBS: 'CONFLICT',

  CLUB_ID_NOT_MATCHING: 'UNPROCESSABLE_CONTENT',
  CLUB_MISMATCH: 'UNPROCESSABLE_CONTENT',
  INVALID_DOUBLES_PAIR: 'UNPROCESSABLE_CONTENT',
  INVALID_UNITS_ORDER: 'UNPROCESSABLE_CONTENT',
  INVALID_UNIT_IN_PAIRING: 'UNPROCESSABLE_CONTENT',
  NOT_DOUBLES_TOURNAMENT: 'UNPROCESSABLE_CONTENT',
  NOT_SOLO_TOURNAMENT: 'UNPROCESSABLE_CONTENT',
  NOT_SWISS_TOURNAMENT: 'UNPROCESSABLE_CONTENT',
  UNSUPPORTED_TOURNAMENT_FORMAT: 'UNPROCESSABLE_CONTENT',

  LONG_CLUB_NAME: 'BAD_REQUEST',
  MAX_50: 'BAD_REQUEST',
  MAX_NICKNAME_LENGTH: 'BAD_REQUEST',
  MAX_PEAK_RATING: 'BAD_REQUEST',
  MAX_RATING: 'BAD_REQUEST',
  MIN_NICKNAME_LENGTH: 'BAD_REQUEST',
  MIN_PEAK_RATING: 'BAD_REQUEST',
  MIN_RATING: 'BAD_REQUEST',
  SHORT_CLUB_NAME: 'BAD_REQUEST',
  TEAM_PLAYERS_SHOULD_BE_DIFFERENT: 'BAD_REQUEST',
  TIME_TRAVEL: 'BAD_REQUEST',
  TOURNAMENT_UNIT_IDS_NOT_UNIQUE: 'BAD_REQUEST',

  UNKNOWN_ERROR: 'INTERNAL_SERVER_ERROR',
  CONFIG_ERROR: 'INTERNAL_SERVER_ERROR',
  CLUB_NOT_CREATED: 'INTERNAL_SERVER_ERROR',
  CLUB_NOT_DELETED: 'INTERNAL_SERVER_ERROR',
  DATABASE_MIGRATION_ERROR: 'INTERNAL_SERVER_ERROR',
  NO_TOURNAMENT_DATA: 'INTERNAL_SERVER_ERROR',
  NO_UNITS_DATA: 'INTERNAL_SERVER_ERROR',
  PAIRING_GENERATOR_ERROR: 'INTERNAL_SERVER_ERROR',
  PLAYER_NOT_CREATED: 'INTERNAL_SERVER_ERROR',
  PLAYER_NOT_EDITED: 'INTERNAL_SERVER_ERROR',
  POSSIBLE_PLAYERS_NOT_LOADED: 'INTERNAL_SERVER_ERROR',
  RATING_CALCULATION_ERROR: 'INTERNAL_SERVER_ERROR',
  TOURNAMENT_INFO_NOT_LOADED: 'INTERNAL_SERVER_ERROR',
  TOURNAMENT_NOT_CREATED: 'INTERNAL_SERVER_ERROR',
  TOURNAMENT_UNITS_NOT_LOADED: 'INTERNAL_SERVER_ERROR',
  UNIT_NOT_ADDED: 'INTERNAL_SERVER_ERROR',
  UNIT_NOT_REMOVED: 'INTERNAL_SERVER_ERROR',
  UNIT_NOT_WITHDRAWN: 'INTERNAL_SERVER_ERROR',
  UNIT_PLAYERS_NOT_FOUND: 'INTERNAL_SERVER_ERROR',
  USERID_NOT_FOUND_IN_CONTEXT: 'INTERNAL_SERVER_ERROR',
  USERS_NOT_LOADED: 'INTERNAL_SERVER_ERROR',
  WEBSOCKET_FAILED: 'INTERNAL_SERVER_ERROR',
  WEBSOCKET_MESSAGE_NOT_SENT: 'INTERNAL_SERVER_ERROR',

  LICHESS_API_ERROR: 'BAD_GATEWAY',
  LINK_TEAM_ERROR: 'BAD_GATEWAY',

  PASTE_DISABLED: 'METHOD_NOT_SUPPORTED',
  SESSION_VALIDATION_TIMEOUT: 'TIMEOUT',
};

export const getAppErrorTrpcCode = (
  message: AppErrorMessage,
): TRPC_ERROR_CODE_KEY => ERROR_TRPC_CODES[message];

/**
 * @param message - one of the ERRORS.
 * @param options.details - PUBLIC additional details to be attached to the error.
 * @param options.cause - INTERNAL cause of the error.
 */
export class AppError extends TRPCError {
  public readonly details?: string;

  constructor(
    message: AppErrorMessage,
    options?: ErrorOptions & { details?: string },
  ) {
    const { details, ...trpcOptions } = options ?? {};
    super({ code: getAppErrorTrpcCode(message), message, ...trpcOptions });
    this.details = details;
  }
}

export const toAppError = (error: unknown): AppError => {
  if (error instanceof AppError) return error;
  return new AppError('UNKNOWN_ERROR', { cause: error });
};

export const getAppErrorMessage = (error: unknown): AppErrorMessage => {
  if (error instanceof AppError) return error.message as AppErrorMessage;
  if (error instanceof Error && isAppErrorMessage(error.message)) {
    return error.message;
  }
  if (isAppErrorMessage(error)) return error;
  return 'UNKNOWN_ERROR';
};
